/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MusicApp;

import sun.audio.*;
import java.io.*;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;
/**
 *
 * @author Sparsh
 */
public class MusicApp extends javax.swing.JFrame {

    /**
     * Creates new form MusicApp
     */
    public MusicApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        uc = new javax.swing.JButton();
        f1 = new javax.swing.JButton();
        ud = new javax.swing.JButton();
        d = new javax.swing.JButton();
        e = new javax.swing.JButton();
        uf = new javax.swing.JButton();
        f = new javax.swing.JButton();
        music = new javax.swing.JCheckBox();
        drum = new javax.swing.JCheckBox();
        ug = new javax.swing.JButton();
        ub = new javax.swing.JButton();
        g = new javax.swing.JButton();
        a = new javax.swing.JButton();
        b = new javax.swing.JButton();
        uc1 = new javax.swing.JButton();
        ud1 = new javax.swing.JButton();
        c1 = new javax.swing.JButton();
        d1 = new javax.swing.JButton();
        e1 = new javax.swing.JButton();
        c = new javax.swing.JButton();
        song2 = new javax.swing.JButton();
        song3 = new javax.swing.JButton();
        song1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1360, 800));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 24));
        jPanel1.setLayout(null);

        uc.setBackground(new java.awt.Color(0, 0, 0));
        uc.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        uc.setForeground(new java.awt.Color(255, 255, 255));
        uc.setText("C#");
        uc.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        uc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ucActionPerformed(evt);
            }
        });
        jPanel1.add(uc);
        uc.setBounds(120, 180, 80, 190);

        f1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        f1.setText("F1");
        f1.setVerifyInputWhenFocusTarget(false);
        f1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        f1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f1ActionPerformed(evt);
            }
        });
        jPanel1.add(f1);
        f1.setBounds(970, 180, 90, 350);

        ud.setBackground(new java.awt.Color(0, 0, 0));
        ud.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ud.setForeground(new java.awt.Color(255, 255, 255));
        ud.setText("D#");
        ud.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                udActionPerformed(evt);
            }
        });
        jPanel1.add(ud);
        ud.setBounds(220, 180, 80, 190);

        d.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        d.setText("D");
        d.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });
        jPanel1.add(d);
        d.setBounds(160, 180, 90, 350);

        e.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        e.setText("E");
        e.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eActionPerformed(evt);
            }
        });
        jPanel1.add(e);
        e.setBounds(250, 180, 90, 350);

        uf.setBackground(new java.awt.Color(0, 0, 0));
        uf.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        uf.setForeground(new java.awt.Color(255, 255, 255));
        uf.setText("F#");
        uf.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        uf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ufActionPerformed(evt);
            }
        });
        jPanel1.add(uf);
        uf.setBounds(380, 180, 80, 190);

        f.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        f.setText("F");
        f.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fActionPerformed(evt);
            }
        });
        jPanel1.add(f);
        f.setBounds(340, 180, 90, 350);

        music.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(music);
        music.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        music.setForeground(new java.awt.Color(255, 255, 255));
        music.setText("Music Notes");
        music.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicActionPerformed(evt);
            }
        });
        jPanel1.add(music);
        music.setBounds(70, 120, 190, 40);

        drum.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(drum);
        drum.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        drum.setForeground(new java.awt.Color(255, 255, 255));
        drum.setText("Steel Drum");
        drum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drumActionPerformed(evt);
            }
        });
        jPanel1.add(drum);
        drum.setBounds(890, 120, 170, 37);

        ug.setBackground(new java.awt.Color(0, 0, 0));
        ug.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ug.setForeground(new java.awt.Color(255, 255, 255));
        ug.setText("G#");
        ug.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ugActionPerformed(evt);
            }
        });
        jPanel1.add(ug);
        ug.setBounds(480, 180, 80, 190);

        ub.setBackground(new java.awt.Color(0, 0, 0));
        ub.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ub.setForeground(new java.awt.Color(255, 255, 255));
        ub.setText("Bb");
        ub.setToolTipText("");
        ub.setVerifyInputWhenFocusTarget(false);
        ub.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubActionPerformed(evt);
            }
        });
        jPanel1.add(ub);
        ub.setBounds(580, 180, 80, 190);

        g.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        g.setText("G");
        g.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gActionPerformed(evt);
            }
        });
        jPanel1.add(g);
        g.setBounds(430, 180, 90, 350);

        a.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        a.setText("A");
        a.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        jPanel1.add(a);
        a.setBounds(520, 180, 90, 350);

        b.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        b.setText("B");
        b.setVerifyInputWhenFocusTarget(false);
        b.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        jPanel1.add(b);
        b.setBounds(610, 180, 90, 350);

        uc1.setBackground(new java.awt.Color(0, 0, 0));
        uc1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        uc1.setForeground(new java.awt.Color(255, 255, 255));
        uc1.setText("C#1");
        uc1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        uc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uc1ActionPerformed(evt);
            }
        });
        jPanel1.add(uc1);
        uc1.setBounds(750, 180, 80, 190);

        ud1.setBackground(new java.awt.Color(0, 0, 0));
        ud1.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        ud1.setForeground(new java.awt.Color(255, 255, 255));
        ud1.setText("D#1");
        ud1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ud1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ud1ActionPerformed(evt);
            }
        });
        jPanel1.add(ud1);
        ud1.setBounds(840, 180, 80, 190);

        c1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        c1.setText("C1");
        c1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        jPanel1.add(c1);
        c1.setBounds(700, 180, 90, 350);

        d1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        d1.setText("D1");
        d1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        d1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d1ActionPerformed(evt);
            }
        });
        jPanel1.add(d1);
        d1.setBounds(790, 180, 90, 350);

        e1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        e1.setText("E1");
        e1.setVerifyInputWhenFocusTarget(false);
        e1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        e1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e1ActionPerformed(evt);
            }
        });
        jPanel1.add(e1);
        e1.setBounds(880, 180, 90, 350);

        c.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        c.setText("C");
        c.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        jPanel1.add(c);
        c.setBounds(70, 180, 90, 350);

        song2.setBackground(new java.awt.Color(51, 153, 255));
        song2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        song2.setText("Jeena Yahan Marna Yahan ");
        song2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                song2ActionPerformed(evt);
            }
        });
        jPanel1.add(song2);
        song2.setBounds(430, 120, 260, 29);

        song3.setBackground(new java.awt.Color(255, 255, 102));
        song3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        song3.setText("Memories");
        song3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                song3ActionPerformed(evt);
            }
        });
        jPanel1.add(song3);
        song3.setBounds(720, 120, 150, 29);

        song1.setBackground(new java.awt.Color(255, 255, 102));
        song1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        song1.setText("Jab Koi Baat");
        song1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                song1ActionPerformed(evt);
            }
        });
        jPanel1.add(song1);
        song1.setBounds(260, 120, 140, 29);

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 153));
        jLabel1.setText("Piano");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(500, 50, 140, 44);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(70, 70, 1140, 580);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ugActionPerformed
        // TODO add your handling code here:
        InputStream audio;
        if (music.isSelected())
        {
            try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\G_s.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
         if (drum.isSelected())
        {
            try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\Gq_Drum.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_ugActionPerformed

    private void ucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ucActionPerformed
        // TODO add your handling code here:
        
       InputStream audio;
        if (music.isSelected())
        {
            try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\C_s.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
         if (drum.isSelected())
        {
            try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\Cq_Drum.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_ucActionPerformed

    private void musicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_musicActionPerformed

    private void drumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drumActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        // TODO add your handling code here:
        InputStream audio;
        if (music.isSelected())
        {
            try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\C.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
         if (drum.isSelected())
        {
            try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\C_Drum.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_cActionPerformed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
        // TODO add your handling code here:
        InputStream audio;
        if (music.isSelected())
        {
            try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\D.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
         if (drum.isSelected())
        {
            try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\D_Drum.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_dActionPerformed

    private void eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eActionPerformed
        // TODO add your handling code here:
        InputStream audio;
        if (music.isSelected())
        {
            try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\E.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
         if (drum.isSelected())
        {
            try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\E_Drum.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_eActionPerformed

    private void fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fActionPerformed
        // TODO add your handling code here:
        InputStream audio;
        if (music.isSelected())
        {
            try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\F.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
         if (drum.isSelected())
        {
            try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\F_Drum.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_fActionPerformed

    private void gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gActionPerformed
        // TODO add your handling code here:
        InputStream audio;
        if (music.isSelected())
        {
            try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\G.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
         if (drum.isSelected())
        {
            try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\G_Drum.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_gActionPerformed

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
        InputStream audio;
        if (music.isSelected())
        {
            try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\A.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
         if (drum.isSelected())
        {
            try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\A_Drum.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_aActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        // TODO add your handling code here:
        InputStream audio;
        if (music.isSelected())
        {
            try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\B.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
         if (drum.isSelected())
        {
            try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\B_Drum.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_bActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
        InputStream audio;
        if (music.isSelected())
        {
            try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\C1.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
         if (drum.isSelected())
        {
            try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\C1_Drum.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_c1ActionPerformed

    private void d1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d1ActionPerformed
        // TODO add your handling code here:
        InputStream audio;
        if (music.isSelected())
        {
            try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\D1.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
         if (drum.isSelected())
        {
            try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\D1_Drum.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_d1ActionPerformed

    private void e1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e1ActionPerformed
        // TODO add your handling code here:
        InputStream audio;
        if (music.isSelected())
        {
            try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\E1.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
         if (drum.isSelected())
        {
            try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\E1_Drum.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_e1ActionPerformed

    private void f1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f1ActionPerformed
        // TODO add your handling code here:
        InputStream audio;
        if (music.isSelected())
        {
            try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\F1.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
         if (drum.isSelected())
        {
            try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\F1_Drum.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_f1ActionPerformed

    private void udActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_udActionPerformed
        // TODO add your handling code here:
        InputStream audio;
        if (music.isSelected())
        {
            try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\D_s.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
         if (drum.isSelected())
        {
            try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\Dq_Drum.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_udActionPerformed

    private void ufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ufActionPerformed
        // TODO add your handling code here:
        InputStream audio;
        if (music.isSelected())
        {
            try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\F_s.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
         if (drum.isSelected())
        {
            try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\Fq_Drum.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_ufActionPerformed

    private void ubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubActionPerformed
        // TODO add your handling code here:
        InputStream audio;
        if (music.isSelected())
        {
            try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\Bb.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
         if (drum.isSelected())
        {
            try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\Bb_Drum.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_ubActionPerformed

    private void uc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uc1ActionPerformed
        // TODO add your handling code here:
        InputStream audio;
        if (music.isSelected())
        {
            try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\C_s1.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
         if (drum.isSelected())
        {
            try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\Cq1_Drum.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_uc1ActionPerformed

    private void ud1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ud1ActionPerformed
        // TODO add your handling code here:
        InputStream audio;
        if (music.isSelected())
        {
            try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\D_s1.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
         if (drum.isSelected())
        {
            try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\Dq1_Drum.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_ud1ActionPerformed

    private void song2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_song2ActionPerformed
        // TODO add your handling code here:
        InputStream audio;
         try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\song2.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        
        
    }//GEN-LAST:event_song2ActionPerformed

    private void song1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_song1ActionPerformed
        // TODO add your handling code here:
         InputStream audio;
         try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\song1.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_song1ActionPerformed

    private void song3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_song3ActionPerformed
        // TODO add your handling code here:
        InputStream audio;
         try{
                audio=new FileInputStream(new File("C:\\Users\\Sparsh\\Documents\\Music_Note\\song3.wav"));
                AudioStream imusic=new AudioStream(audio);
                AudioPlayer.player.start(imusic);
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_song3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusicApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusicApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusicApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusicApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusicApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a;
    private javax.swing.JButton b;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton c;
    private javax.swing.JButton c1;
    private javax.swing.JButton d;
    private javax.swing.JButton d1;
    private javax.swing.JCheckBox drum;
    private javax.swing.JButton e;
    private javax.swing.JButton e1;
    private javax.swing.JButton f;
    private javax.swing.JButton f1;
    private javax.swing.JButton g;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox music;
    private javax.swing.JButton song1;
    private javax.swing.JButton song2;
    private javax.swing.JButton song3;
    private javax.swing.JButton ub;
    private javax.swing.JButton uc;
    private javax.swing.JButton uc1;
    private javax.swing.JButton ud;
    private javax.swing.JButton ud1;
    private javax.swing.JButton uf;
    private javax.swing.JButton ug;
    // End of variables declaration//GEN-END:variables
}
